name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set current year
        run: echo "YEAR=$(date +%Y)" >> "$GITHUB_ENV"
      - uses: yoshi389111/github-profile-3d-contrib@0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          YEAR: ${{ env.YEAR }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A profile-3d-contrib
          git diff --staged --quiet || git commit -m "chore: update 3d contribution graph"
          git push
